package hu.sparklabs;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.conf.Configured;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapred.JobClient;
import org.apache.hadoop.mapreduce.Job;
import org.apache.hadoop.mapreduce.MRJobConfig;
import org.apache.hadoop.mapreduce.Mapper;
import org.apache.hadoop.mapreduce.OutputFormat;
import org.apache.hadoop.mapreduce.lib.output.FileOutputFormat;
import org.apache.hadoop.mapreduce.lib.output.TextOutputFormat;
import org.apache.hadoop.util.Tool;
import org.apache.hadoop.util.ToolRunner;

import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Random;

/**
 * This program uses map/reduce to just run a distributed job where there is
 * no interaction between the tasks and each task writes a large unsorted
 * random sequence of user data.
 * In order for this program to generate data, we have the following config:
 * <pre>{@code
 * <?xml version="1.0"?>
 * <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
 * <configuration>
 *   <property>
 *     <name>mapreduce.randomwriter.linespermap</name>
 *     <value>1</value>
 *   </property>
 * </configuration>}</pre>
 * <p>
 * To run: spark-submit --class hu.sparklabs.RandomUserDataWriter
 * sparkprocessor-1.0-SNAPSHOT.jar <number of records to be generated> <output folder>
 */
public class RandomUserDataWriter extends Configured implements Tool {

    public static final String LINES_PER_MAP =
            "mapreduce.randomwriter.linespermap";

    static int printUsage() {
        System.out.println("RandomUserDataWriter <number of records to be generated> <output folder>");
        ToolRunner.printGenericCommandUsage(System.out);
        return 2;
    }

    /**
     * User counters
     */
    static enum Counters {RECORDS_WRITTEN}

    static class RandomTextMapper extends Mapper<Text, Text, Text, Text> {

        private long numLinesToWritePerMap;
        private Random random = new Random();

        /**
         * Save the configuration value that we need to write the data.
         */
        public void setup(Context context) {
            Configuration conf = context.getConfiguration();
            numLinesToWritePerMap = conf.getLong(LINES_PER_MAP, 1);
        }

        public void map(Text key, Text value,
                        Context context) throws IOException, InterruptedException {
            for (int i = 0; i < numLinesToWritePerMap; i++) {
                Text keyWords = generateKey();

                context.write(keyWords, new Text(""));

                // Update counters, progress etc.
                context.getCounter(Counters.RECORDS_WRITTEN).increment(1);
                context.setStatus("1 record is written");
            }
        }

        private String randomDateAsString(final DateTimeFormatter formatter) {
            return LocalDate.ofEpochDay(random.nextInt(10000)).format(formatter);
        }

        private Text generateKey() {
            String userDataText = String.format("%s,%s,%s,%s",
                    firstNames[random.nextInt(firstNames.length)],
                    lastNames[random.nextInt(lastNames.length)],
                    locations[random.nextInt(locations.length)],
                    randomDateAsString(DateTimeFormatter.ISO_DATE));
            return new Text(userDataText);
        }

    }

    /**
     * This is the main routine for launching a distributed random write job.
     * The reduce doesn't do anything.
     *
     * @throws IOException
     */
    public int run(String[] args) throws Exception {
        if (args.length == 0) {
            return printUsage();
        }

        long totalLines = Long.parseLong(args[0]);
        long numMaps = 1;
        long linesPerMap = totalLines / numMaps;

        Configuration conf = getConf();
        JobClient client = new JobClient(conf);
        conf.setLong(LINES_PER_MAP, linesPerMap);
        conf.setLong(MRJobConfig.NUM_MAPS, numMaps);

        Job job = Job.getInstance(conf);

        job.setJarByClass(RandomUserDataWriter.class);
        job.setJobName("random-text-writer");

        job.setOutputKeyClass(Text.class);
        job.setOutputValueClass(Text.class);

        job.setInputFormatClass(RandomWriter.RandomInputFormat.class);
        job.setMapperClass(RandomTextMapper.class);

        Class<? extends OutputFormat> outputFormatClass =
                TextOutputFormat.class;

        job.setOutputFormatClass(outputFormatClass);
        FileOutputFormat.setOutputPath(job, new Path(args[1]));

        System.out.println("Running " + numMaps + " maps.");

        // reducer NONE
        job.setNumReduceTasks(0);

        Date startTime = new Date();
        System.out.println("Job started: " + startTime);
        int ret = job.waitForCompletion(true) ? 0 : 1;
        Date endTime = new Date();
        System.out.println("Job ended: " + endTime);
        System.out.println("The job took " +
                (endTime.getTime() - startTime.getTime()) / 1000 +
                " seconds.");

        return ret;
    }

    public static void main(String[] args) throws Exception {
        int res = ToolRunner.run(new Configuration(), new RandomUserDataWriter(), args);
        System.exit(res);
    }

    private static String[] firstNames = {
            "David",
            "John",
            "Paul",
            "Mark",
            "James",
            "Andrew",
            "Scott",
            "Steven",
            "Robert",
            "Stephen",
            "William",
            "Craig",
            "Michael",
            "Stuart",
            "Christopher",
            "Alan",
            "Colin",
            "Brian",
            "Kevin",
            "Gary",
            "Richard",
            "Derek",
            "Martin",
            "Thomas",
            "Neil",
            "Barry",
            "Ian",
            "Jason",
            "Iain",
            "Gordon",
            "Alexander",
            "Graeme",
            "Peter",
            "Darren",
            "Graham",
            "George",
            "Kenneth",
            "Allan",
            "Simon",
            "Douglas",
            "Keith",
            "Lee",
            "Anthony",
            "Grant",
            "Ross",
            "Jonathan",
            "Gavin",
            "Nicholas",
            "Joseph",
            "Stewart",
            "Daniel",
            "Edward",
            "Matthew",
            "Donald",
            "Fraser",
            "Garry",
            "Malcolm",
            "Charles",
            "Duncan",
            "Alistair",
            "Raymond",
            "Philip",
            "Ronald",
            "Ewan",
            "Ryan",
            "Francis",
            "Bruce",
            "Patrick",
            "Alastair",
            "Bryan",
            "Marc",
            "Jamie",
            "Hugh",
            "Euan",
            "Gerard",
            "Sean",
            "Wayne",
            "Adam",
            "Calum",
            "Alasdair",
            "Robin",
            "Greig",
            "Angus",
            "Russell",
            "Cameron",
            "Roderick",
            "Norman",
            "Murray",
            "Gareth",
            "Dean",
            "Eric",
            "Adrian",
            "Gregor",
            "Samuel",
            "Gerald",
            "Henry",
            "Justin",
            "Benjamin",
            "Shaun",
            "Callum",
            "Campbell",
            "Frank",
            "Roy",
            "Timothy",
            "David",
            "John",
            "Paul",
            "James",
            "Mark",
            "Scott",
            "Andrew",
            "Steven",
            "Robert",
            "Stephen",
            "Craig",
            "Christopher",
            "Alan",
            "Michael",
            "Stuart",
            "William",
            "Kevin",
            "Colin",
            "Brian",
            "Derek",
            "Neil",
            "Richard",
            "Gary",
            "Barry",
            "Martin",
            "Thomas",
            "Ian",
            "Gordon",
            "Kenneth",
            "Alexander",
            "Graeme",
            "Peter",
            "Iain",
            "Graham",
            "Jason",
            "George",
            "Allan",
            "Keith",
            "Darren",
            "Simon",
            "Douglas",
            "Ross",
            "Stewart",
            "Lee",
            "Grant",
            "Nicholas",
            "Joseph",
            "Gavin",
            "Anthony",
            "Jonathan",
            "Daniel",
            "Fraser",
            "Matthew",
            "Donald",
            "Malcolm",
            "Alistair",
            "Edward",
            "Raymond",
            "Charles",
            "Philip",
            "Bruce",
            "Garry",
            "Jamie",
            "Ryan",
            "Bryan",
            "Francis",
            "Alastair",
            "Duncan",
            "Patrick",
            "Ronald",
            "Alasdair",
            "Ewan",
            "Marc",
            "Wayne",
            "Hugh",
            "Robin",
            "Sean",
            "Calum",
            "Euan",
            "Adam",
            "Russell",
            "Cameron",
            "Gerard",
            "Murray",
            "Norman",
            "Angus",
            "Greig",
            "Justin",
            "Gregor",
            "Gerald",
            "Roderick",
            "Roy",
            "Benjamin",
            "Timothy",
            "Dean",
            "Samuel",
            "Greg",
            "Shaun",
            "Adrian",
            "Campbell",
            "David",
            "John",
            "Paul",
            "James",
            "Andrew",
            "Steven",
            "Scott",
            "Mark",
            "Robert",
            "Stephen",
            "Craig",
            "Christopher",
            "Stuart",
            "Alan",
            "William",
            "Michael",
            "Kevin",
            "Colin",
            "Brian",
            "Derek",
            "Neil",
            "Richard",
            "Martin",
            "Gary",
            "Ross",
            "Thomas",
            "Ian",
            "Iain",
            "Barry",
            "Gordon",
            "Graeme",
            "Graham",
            "Alexander",
            "Peter",
            "Kenneth",
            "Simon",
            "Allan",
            "Darren",
            "George",
            "Douglas",
            "Jason",
            "Lee",
            "Gavin",
            "Anthony",
            "Jonathan",
            "Stewart",
            "Jamie",
            "Keith",
            "Matthew",
            "Joseph",
            "Daniel",
            "Edward",
            "Nicholas",
            "Grant",
            "Ryan",
            "Philip",
            "Alistair",
            "Donald",
            "Charles",
            "Duncan",
            "Garry",
            "Malcolm",
            "Raymond",
            "Bryan",
            "Ewan",
            "Fraser",
            "Alastair",
            "Euan",
            "Patrick",
            "Bruce",
            "Ronald",
            "Greig",
            "Hugh",
            "Francis",
            "Gerard",
            "Russell",
            "Alasdair",
            "Adam",
            "Marc",
            "Sean",
            "Benjamin",
            "Gregor",
            "Calum",
            "Wayne",
            "Robin",
            "Roderick",
            "Murray",
            "Greg",
            "Angus",
            "Cameron",
            "Gerald",
            "Shaun",
            "Samuel",
            "Timothy",
            "Liam",
            "Campbell",
            "Gareth",
            "Niall",
            "Dean",
            "Justin",
            "David",
            "John",
            "Paul",
            "James",
            "Andrew",
            "Steven",
            "Scott",
            "Mark",
            "Robert",
            "Christopher",
            "Craig",
            "Stuart",
            "Kevin",
            "Alan",
            "Michael",
            "Stephen",
            "William",
            "Colin",
            "Brian",
            "Neil",
            "Richard",
            "Ross",
            "Thomas",
            "Gary",
            "Derek",
            "Iain",
            "Gordon",
            "Graeme",
            "Martin",
            "Barry",
            "Gavin",
            "Ian",
            "Kenneth",
            "Alexander",
            "Peter",
            "Graham",
            "Allan",
            "Darren",
            "Jamie",
            "Simon",
            "Lee",
            "George",
            "Keith",
            "Stewart",
            "Douglas",
            "Jonathan",
            "Matthew",
            "Daniel",
            "Grant",
            "Joseph",
            "Jason",
            "Anthony",
            "Ryan",
            "Edward",
            "Fraser",
            "Donald",
            "Charles",
            "Garry",
            "Duncan",
            "Nicholas",
            "Raymond",
            "Alistair",
            "Bryan",
            "Philip",
            "Alastair",
            "Malcolm",
            "Alasdair",
            "Russell",
            "Patrick",
            "Euan",
            "Ewan",
            "Gareth",
            "Bruce",
            "Adam",
            "Gerard",
            "Greig",
            "Marc",
            "Sean",
            "Robin",
            "Ronald",
            "Benjamin",
            "Francis",
            "Gregor",
            "Greg",
            "Hugh",
            "Calum",
            "Shaun",
            "Cameron",
            "Roderick",
            "Angus",
            "Gerald",
            "Rory",
            "Samuel",
            "Wayne",
            "Murray",
            "Norman",
            "Timothy",
            "Dean",
            "Martyn",
            "Roy",
            "Wesley",
            "David",
            "John",
            "Andrew",
            "Paul",
            "James",
            "Scott",
            "Christopher",
            "Steven",
            "Michael",
            "Mark",
            "Robert",
            "Craig",
            "Kevin",
            "Stuart",
            "Alan",
            "Stephen",
            "William",
            "Ross",
            "Colin",
            "Brian",
            "Richard",
            "Barry",
            "Neil",
            "Derek",
            "Gordon",
            "Thomas",
            "Graeme",
            "Martin",
            "Peter",
            "Gary",
            "Iain",
            "Graham",
            "Ian",
            "Kenneth",
            "Alexander",
            "Allan",
            "Jamie",
            "Gavin",
            "Darren",
            "George",
            "Douglas",
            "Simon",
            "Stewart",
            "Daniel",
            "Keith",
            "Lee",
            "Ryan",
            "Joseph",
            "Matthew",
            "Grant",
            "Anthony",
            "Jason",
            "Jonathan",
            "Duncan",
            "Fraser",
            "Donald",
            "Garry",
            "Nicholas",
            "Alistair",
            "Bryan",
            "Charles",
            "Raymond",
            "Philip",
            "Marc",
            "Euan",
            "Edward",
            "Gareth",
            "Sean",
            "Adam",
            "Alasdair",
            "Alastair",
            "Greig",
            "Ronald",
            "Malcolm",
            "Patrick",
            "Ewan",
            "Russell",
            "Greg",
            "Gregor",
            "Robin",
            "Benjamin",
            "Bruce",
            "Gerard",
            "Francis",
            "Hugh",
            "Calum",
            "Cameron",
            "Shaun",
            "Wayne",
            "Samuel",
            "Murray",
            "Roderick",
            "Barrie",
            "Callum",
            "Angus",
            "Liam",
            "Rory",
            "Niall",
            "Timothy",
            "Antony",
            "David",
            "John",
            "Andrew",
            "Paul",
            "James",
            "Christopher",
            "Steven",
            "Scott",
            "Mark",
            "Robert",
            "Craig",
            "Kevin",
            "Michael",
            "Stuart",
            "Stephen",
            "Alan",
            "Colin",
            "William",
            "Brian",
            "Barry",
            "Ross",
            "Gary",
            "Martin",
            "Thomas",
            "Richard",
            "Graeme",
            "Neil",
            "Peter",
            "Iain",
            "Gordon",
            "Derek",
            "Ian",
            "Alexander",
            "Kenneth",
            "Graham",
            "Allan",
            "Darren",
            "Gavin",
            "Jamie",
            "Douglas",
            "Ryan",
            "Simon",
            "George",
            "Matthew",
            "Lee",
            "Stewart",
            "Keith",
            "Daniel",
            "Anthony",
            "Grant",
            "Gareth",
            "Jonathan",
            "Joseph",
            "Alistair",
            "Charles",
            "Edward",
            "Fraser",
            "Duncan",
            "Garry",
            "Bryan",
            "Ewan",
            "Nicholas",
            "Donald",
            "Philip",
            "Alastair",
            "Adam",
            "Jason",
            "Euan",
            "Russell",
            "Sean",
            "Malcolm",
            "Patrick",
            "Raymond",
            "Alasdair",
            "Liam",
            "Greig",
            "Gregor",
            "Ronald",
            "Greg",
            "Shaun",
            "Wayne",
            "Bruce",
            "Marc",
            "Robin",
            "Cameron",
            "Francis",
            "Angus",
            "Gerard",
            "Kris",
            "Calum",
            "Benjamin",
            "Rory",
            "Dean",
            "Timothy",
            "Samuel",
            "Niall",
            "Hugh",
            "Lewis",
            "Murray",
            "Justin",
            "Roderick",
            "David",
            "John",
            "Andrew",
            "James",
            "Christopher",
            "Paul",
            "Steven",
            "Kevin",
            "Robert",
            "Scott",
            "Craig",
            "Michael",
            "Mark",
            "Stuart",
            "Stephen",
            "Alan",
            "William",
            "Gary",
            "Ross",
            "Colin",
            "Brian",
            "Barry",
            "Richard",
            "Martin",
            "Thomas",
            "Neil",
            "Peter",
            "Iain",
            "Graeme",
            "Ian",
            "Gordon",
            "Alexander",
            "Ryan",
            "Derek",
            "Kenneth",
            "Allan",
            "Jamie",
            "Graham",
            "Gavin",
            "Darren",
            "Stewart",
            "Gareth",
            "Jonathan",
            "Daniel",
            "Douglas",
            "Grant",
            "Lee",
            "George",
            "Joseph",
            "Simon",
            "Matthew",
            "Keith",
            "Anthony",
            "Fraser",
            "Garry",
            "Alistair",
            "Bryan",
            "Philip",
            "Adam",
            "Sean",
            "Duncan",
            "Edward",
            "Charles",
            "Ewan",
            "Russell",
            "Donald",
            "Patrick",
            "Alastair",
            "Euan",
            "Jason",
            "Nicholas",
            "Marc",
            "Raymond",
            "Malcolm",
            "Greig",
            "Alasdair",
            "Greg",
            "Liam",
            "Shaun",
            "Francis",
            "Ronald",
            "Benjamin",
            "Cameron",
            "Dean",
            "Niall",
            "Gerard",
            "Murray",
            "Robin",
            "Timothy",
            "Bruce",
            "Hugh",
            "Calum",
            "Kris",
            "Wayne",
            "Roderick",
            "Samuel",
            "Martyn",
            "Angus",
            "Gregor",
            "Jon",
            "Rory",
            "David",
            "John",
            "Andrew",
            "Christopher",
            "James",
            "Paul",
            "Steven",
            "Craig",
            "Michael",
            "Scott",
            "Kevin",
            "Robert",
            "Mark",
            "Stuart",
            "Stephen",
            "Gary",
            "Alan",
            "William",
            "Ross",
            "Colin",
            "Martin",
            "Thomas",
            "Barry",
            "Brian",
            "Neil",
            "Richard",
            "Graeme",
            "Peter",
            "Iain",
            "Gordon",
            "Ian",
            "Alexander",
            "Darren",
            "Derek",
            "Graham",
            "Ryan",
            "Jamie",
            "Kenneth",
            "Allan",
            "Gavin",
            "Jonathan",
            "Daniel",
            "George",
            "Douglas",
            "Stewart",
            "Matthew",
            "Anthony",
            "Keith",
            "Grant",
            "Sean",
            "Simon",
            "Gareth",
            "Garry",
            "Lee",
            "Fraser",
            "Alistair",
            "Adam",
            "Joseph",
            "Nicholas",
            "Bryan",
            "Charles",
            "Duncan",
            "Philip",
            "Russell",
            "Donald",
            "Edward",
            "Marc",
            "Alastair",
            "Greg",
            "Euan",
            "Raymond",
            "Shaun",
            "Ewan",
            "Jason",
            "Patrick",
            "Alasdair",
            "Gerard",
            "Malcolm",
            "Calum",
            "Liam",
            "Bruce",
            "Ronald",
            "Kris",
            "Hugh",
            "Lewis",
            "Dean",
            "Greig",
            "Benjamin",
            "Wayne",
            "Martyn",
            "Niall",
            "Callum",
            "Francis",
            "Cameron",
            "Gregor",
            "Angus",
            "Aaron",
            "Blair",
            "Dale",
            "Samuel",
            "Timothy",
            "David",
            "Christopher",
            "John",
            "Andrew",
            "James",
            "Paul",
            "Steven",
            "Craig",
            "Scott",
            "Mark",
            "Michael",
            "Robert",
            "Kevin",
            "Stuart",
            "William",
            "Alan",
            "Stephen",
            "Gary",
            "Ross",
            "Martin",
            "Colin",
            "Richard",
            "Thomas",
            "Brian",
            "Barry",
            "Neil",
            "Graeme",
            "Gordon",
            "Ian",
            "Iain",
            "Peter",
            "Darren",
            "Alexander",
            "Jamie",
            "Ryan",
            "Graham",
            "Jonathan",
            "Derek",
            "Kenneth",
            "Daniel",
            "Allan",
            "Matthew",
            "Gavin",
            "Lee",
            "Stewart",
            "Douglas",
            "George",
            "Sean",
            "Nicholas",
            "Simon",
            "Fraser",
            "Keith",
            "Anthony",
            "Joseph",
            "Adam",
            "Gareth",
            "Grant",
            "Bryan",
            "Duncan",
            "Philip",
            "Euan",
            "Alistair",
            "Garry",
            "Ewan",
            "Charles",
            "Edward",
            "Jason",
            "Marc",
            "Shaun",
            "Donald",
            "Russell",
            "Alastair",
            "Patrick",
            "Calum",
            "Liam",
            "Alasdair",
            "Greg",
            "Callum",
            "Raymond",
            "Benjamin",
            "Gerard",
            "Malcolm",
            "Cameron",
            "Aaron",
            "Ronald",
            "Bruce",
            "Greig",
            "Lewis",
            "Francis",
            "Dean",
            "Gregor",
            "Niall",
            "Jordan",
            "Kris",
            "Martyn",
            "Robin",
            "Samuel",
            "Blair",
            "Hugh",
            "Mohammed",
            "Murray",
            "Wayne",
            "David",
            "Christopher",
            "Andrew",
            "John",
            "James",
            "Craig",
            "Steven",
            "Paul",
            "Michael",
            "Scott",
            "Robert",
            "Mark",
            "William",
            "Kevin",
            "Stuart",
            "Stephen",
            "Alan",
            "Gary",
            "Ross",
            "Colin",
            "Richard",
            "Martin",
            "Thomas",
            "Neil",
            "Ryan",
            "Graeme",
            "Brian",
            "Peter",
            "Gordon",
            "Darren",
            "Ian",
            "Jamie",
            "Alexander",
            "Iain",
            "Graham",
            "Barry",
            "Allan",
            "Jonathan",
            "Daniel",
            "Gavin",
            "Derek",
            "Kenneth",
            "Sean",
            "Matthew",
            "Lee",
            "George",
            "Nicholas",
            "Anthony",
            "Stewart",
            "Fraser",
            "Douglas",
            "Keith",
            "Joseph",
            "Grant",
            "Marc",
            "Adam",
            "Simon",
            "Alistair",
            "Garry",
            "Alastair",
            "Bryan",
            "Liam",
            "Jason",
            "Duncan",
            "Euan",
            "Charles",
            "Greg",
            "Edward",
            "Philip",
            "Russell",
            "Shaun",
            "Gareth",
            "Ewan",
            "Calum",
            "Callum",
            "Donald",
            "Cameron",
            "Raymond",
            "Patrick",
            "Alasdair",
            "Dean",
            "Greig",
            "Lewis",
            "Benjamin",
            "Malcolm",
            "Niall",
            "Gerard",
            "Martyn",
            "Jordan",
            "Aaron"
    };

    private static String[] lastNames = {
            "Smith",
            "Johnson",
            "Williams",
            "Brown",
            "Jones",
            "Miller",
            "Davis",
            "Garcia",
            "Rodriguez",
            "Wilson",
            "Martinez",
            "Anderson",
            "Taylor",
            "Thomas",
            "Hernandez",
            "Moore",
            "Martin",
            "Jackson",
            "Thompson",
            "White",
            "Lopez",
            "Lee",
            "Gonzalez",
            "Harris",
            "Clark",
            "Lewis",
            "Robinson",
            "Walker",
            "Perez",
            "Hall",
            "Young",
            "Allen",
            "Sanchez",
            "Wright",
            "King",
            "Scott",
            "Green",
            "Baker",
            "Adams",
            "Nelson",
            "Hill",
            "Ramirez",
            "Campbell",
            "Mitchell",
            "Roberts",
            "Carter",
            "Phillips",
            "Evans",
            "Turner",
            "Torres",
            "Parker",
            "Collins",
            "Edwards",
            "Stewart",
            "Flores",
            "Morris",
            "Nguyen",
            "Murphy",
            "Rivera",
            "Cook",
            "Rogers",
            "Morgan",
            "Peterson",
            "Cooper",
            "Reed",
            "Bailey",
            "Bell",
            "Gomez",
            "Kelly",
            "Howard",
            "Ward",
            "Cox",
            "Diaz",
            "Richardson",
            "Wood",
            "Watson",
            "Brooks",
            "Bennett",
            "Gray",
            "James",
            "Reyes",
            "Cruz",
            "Hughes",
            "Price",
            "Myers",
            "Long",
            "Foster",
            "Sanders",
            "Ross",
            "Morales",
            "Powell",
            "Sullivan",
            "Russell",
            "Ortiz",
            "Jenkins",
            "Gutierrez",
            "Perry",
            "Butler",
            "Barnes",
            "Fisher",
            "Henderson",
            "Coleman",
            "Simmons",
            "Patterson",
            "Jordan",
            "Reynolds",
            "Hamilton",
            "Graham",
            "Kim",
            "Gonzales",
            "Alexander",
            "Ramos",
            "Wallace",
            "Griffin",
            "West",
            "Cole",
            "Hayes",
            "Chavez",
            "Gibson",
            "Bryant",
            "Ellis",
            "Stevens",
            "Murray",
            "Ford",
            "Marshall",
            "Owens",
            "Mcdonald",
            "Harrison",
            "Ruiz",
            "Kennedy",
            "Wells",
            "Alvarez",
            "Woods",
            "Mendoza",
            "Castillo",
            "Olson",
            "Webb",
            "Washington",
            "Tucker",
            "Freeman",
            "Burns",
            "Henry",
            "Vasquez",
            "Snyder",
            "Simpson",
            "Crawford",
            "Jimenez",
            "Porter",
            "Mason",
            "Shaw",
            "Gordon",
            "Wagner",
            "Hunter",
            "Romero",
            "Hicks",
            "Dixon",
            "Hunt",
            "Palmer",
            "Robertson",
            "Black",
            "Holmes",
            "Stone",
            "Meyer",
            "Boyd",
            "Mills",
            "Warren",
            "Fox",
            "Rose",
            "Rice",
            "Moreno",
            "Schmidt",
            "Patel",
            "Ferguson",
            "Nichols",
            "Herrera",
            "Medina",
            "Ryan",
            "Fernandez",
            "Weaver",
            "Daniels",
            "Stephens",
            "Gardner",
            "Payne",
            "Kelley",
            "Dunn",
            "Pierce",
            "Arnold",
            "Tran",
            "Spencer",
            "Peters",
            "Hawkins",
            "Grant",
            "Hansen",
            "Castro",
            "Hoffman",
            "Hart",
            "Elliott",
            "Cunningham",
            "Knight",
            "Bradley",
            "Carroll",
            "Hudson",
            "Duncan",
            "Armstrong",
            "Berry",
            "Andrews",
            "Johnston",
            "Ray",
            "Lane",
            "Riley",
            "Carpenter",
            "Perkins",
            "Aguilar",
            "Silva",
            "Richards",
            "Willis",
            "Matthews",
            "Chapman",
            "Lawrence",
            "Garza",
            "Vargas",
            "Watkins",
            "Wheeler",
            "Larson",
            "Carlson",
            "Harper",
            "George",
            "Greene",
            "Burke",
            "Guzman",
            "Morrison",
            "Munoz",
            "Jacobs",
            "Obrien",
            "Lawson",
            "Franklin",
            "Lynch",
            "Bishop",
            "Carr",
            "Salazar",
            "Austin",
            "Mendez",
            "Gilbert",
            "Jensen",
            "Williamson",
            "Montgomery",
            "Harvey",
            "Oliver",
            "Howell",
            "Dean",
            "Hanson",
            "Weber",
            "Garrett",
            "Sims",
            "Burton",
            "Fuller",
            "Soto",
            "Mccoy",
            "Welch",
            "Chen",
            "Schultz",
            "Walters",
            "Reid",
            "Fields",
            "Walsh",
            "Little",
            "Fowler",
            "Bowman",
            "Davidson",
            "May",
            "Day",
            "Schneider",
            "Newman",
            "Brewer",
            "Lucas",
            "Holland",
            "Wong",
            "Banks",
            "Santos",
            "Curtis",
            "Pearson",
            "Delgado",
            "Valdez",
            "Pena",
            "Rios",
            "Douglas",
            "Sandoval",
            "Barrett",
            "Hopkins",
            "Keller",
            "Guerrero",
            "Stanley",
            "Bates",
            "Alvarado",
            "Beck",
            "Ortega",
            "Wade",
            "Estrada",
            "Contreras",
            "Barnett",
            "Caldwell",
            "Santiago",
            "Lambert",
            "Powers",
            "Chambers",
            "Nunez",
            "Craig",
            "Leonard",
            "Lowe",
            "Rhodes",
            "Byrd",
            "Gregory",
            "Shelton",
            "Frazier",
            "Becker",
            "Maldonado",
            "Fleming",
            "Vega",
            "Sutton",
            "Cohen",
            "Jennings",
            "Parks",
            "Mcdaniel",
            "Watts",
            "Barker",
            "Norris",
            "Vaughn",
            "Vazquez",
            "Holt",
            "Schwartz",
            "Steele",
            "Benson",
            "Neal",
            "Dominguez",
            "Horton",
            "Terry",
            "Wolfe",
            "Hale",
            "Lyons",
            "Graves",
            "Haynes",
            "Miles",
            "Park",
            "Warner",
            "Padilla",
            "Bush",
            "Thornton",
            "Mccarthy",
            "Mann",
            "Zimmerman",
            "Erickson",
            "Fletcher",
            "Mckinney",
            "Page",
            "Dawson",
            "Joseph",
            "Marquez",
            "Reeves",
            "Klein",
            "Espinoza",
            "Baldwin",
            "Moran",
            "Love",
            "Robbins",
            "Higgins",
            "Ball",
            "Cortez",
            "Le",
            "Griffith",
            "Bowen",
            "Sharp",
            "Cummings",
            "Ramsey",
            "Hardy",
            "Swanson",
            "Barber",
            "Acosta",
            "Luna",
            "Chandler",
            "Blair",
            "Daniel",
            "Cross",
            "Simon",
            "Dennis",
            "Oconnor",
            "Quinn",
            "Gross",
            "Navarro",
            "Moss",
            "Fitzgerald",
            "Doyle",
            "Mclaughlin",
            "Rojas",
            "Rodgers",
            "Stevenson",
            "Singh",
            "Yang",
            "Figueroa",
            "Harmon",
            "Newton",
            "Paul",
            "Manning",
            "Garner",
            "Mcgee",
            "Reese",
            "Francis",
            "Burgess",
            "Adkins",
            "Goodman",
            "Curry",
            "Brady",
            "Christensen",
            "Potter",
            "Walton",
            "Goodwin",
            "Mullins",
            "Molina",
            "Webster",
            "Fischer",
            "Campos",
            "Avila",
            "Sherman",
            "Todd",
            "Chang",
            "Blake",
            "Malone",
            "Wolf",
            "Hodges",
            "Juarez",
            "Gill",
            "Farmer",
            "Hines",
            "Gallagher",
            "Duran",
            "Hubbard",
            "Cannon",
            "Miranda",
            "Wang",
            "Saunders",
            "Tate",
            "Mack",
            "Hammond",
            "Carrillo",
            "Townsend",
            "Wise",
            "Ingram",
            "Barton",
            "Mejia",
            "Ayala",
            "Schroeder",
            "Hampton",
            "Rowe",
            "Parsons",
            "Frank",
            "Waters",
            "Strickland",
            "Osborne",
            "Maxwell",
            "Chan",
            "Deleon",
            "Norman",
            "Harrington",
            "Casey",
            "Patton",
            "Logan",
            "Bowers",
            "Mueller",
            "Glover",
            "Floyd",
            "Hartman",
            "Buchanan",
            "Cobb",
            "French",
            "Kramer",
            "Mccormick",
            "Clarke",
            "Tyler",
            "Gibbs",
            "Moody",
            "Conner",
            "Sparks",
            "Mcguire",
            "Leon",
            "Bauer",
            "Norton",
            "Pope",
            "Flynn",
            "Hogan",
            "Robles",
            "Salinas",
            "Yates",
            "Lindsey",
            "Lloyd",
            "Marsh",
            "Mcbride",
            "Owen",
            "Solis",
            "Pham",
            "Lang",
            "Pratt",
            "Lara",
            "Brock",
            "Ballard",
            "Trujillo",
            "Shaffer",
            "Drake",
            "Roman",
            "Aguirre",
            "Morton",
            "Stokes",
            "Lamb",
            "Pacheco",
            "Patrick",
            "Cochran",
            "Shepherd",
            "Cain",
            "Burnett",
            "Hess",
            "Li",
            "Cervantes",
            "Olsen",
            "Briggs",
            "Ochoa",
            "Cabrera",
            "Velasquez",
            "Montoya",
            "Roth",
            "Meyers",
            "Cardenas",
            "Fuentes",
            "Weiss",
            "Hoover",
            "Wilkins",
            "Nicholson",
            "Underwood",
            "Short",
            "Carson",
            "Morrow",
            "Colon",
            "Holloway",
            "Summers",
            "Bryan",
            "Petersen",
            "Mckenzie",
            "Serrano",
            "Wilcox",
            "Carey",
            "Clayton",
            "Poole",
            "Calderon",
            "Gallegos",
            "Greer",
            "Rivas",
            "Guerra",
            "Decker",
            "Collier",
            "Wall",
            "Whitaker",
            "Bass",
            "Flowers",
            "Davenport",
            "Conley",
            "Houston",
            "Huff",
            "Copeland",
            "Hood",
            "Monroe",
            "Massey",
            "Roberson",
            "Combs",
            "Franco",
            "Larsen",
            "Pittman",
            "Randall",
            "Skinner",
            "Wilkinson",
            "Kirby",
            "Cameron",
            "Bridges",
            "Anthony",
            "Richard",
            "Kirk",
            "Bruce",
            "Singleton",
            "Mathis",
            "Bradford",
            "Boone",
            "Abbott",
            "Charles",
            "Allison",
            "Sweeney",
            "Atkinson",
            "Horn",
            "Jefferson",
            "Rosales",
            "York",
            "Christian",
            "Phelps",
            "Farrell",
            "Castaneda",
            "Nash",
            "Dickerson",
            "Bond",
            "Wyatt",
            "Foley",
            "Chase",
            "Gates",
            "Vincent",
            "Mathews",
            "Hodge",
            "Garrison",
            "Trevino",
            "Villarreal",
            "Heath",
            "Dalton",
            "Valencia",
            "Callahan",
            "Hensley",
            "Atkins",
            "Huffman",
            "Roy",
            "Boyer",
            "Shields",
            "Lin",
            "Hancock",
            "Grimes",
            "Glenn",
            "Cline",
            "Delacruz",
            "Camacho",
            "Dillon",
            "Parrish",
            "Oneill",
            "Melton",
            "Booth",
            "Kane",
            "Berg",
            "Harrell",
            "Pitts",
            "Savage",
            "Wiggins",
            "Brennan",
            "Salas",
            "Marks",
            "Russo",
            "Sawyer",
            "Baxter",
            "Golden",
            "Hutchinson",
            "Liu",
            "Walter",
            "Mcdowell",
            "Wiley",
            "Rich",
            "Humphrey",
            "Johns",
            "Koch",
            "Suarez",
            "Hobbs",
            "Beard",
            "Gilmore",
            "Ibarra",
            "Keith",
            "Macias",
            "Khan",
            "Andrade",
            "Ware",
            "Stephenson",
            "Henson",
            "Wilkerson",
            "Dyer",
            "Mcclure",
            "Blackwell",
            "Mercado",
            "Tanner",
            "Eaton",
            "Clay",
            "Barron",
            "Beasley",
            "Oneal",
            "Preston",
            "Small",
            "Wu",
            "Zamora",
            "Macdonald",
            "Vance",
            "Snow",
            "Mcclain",
            "Stafford",
            "Orozco",
            "Barry",
            "English",
            "Shannon",
            "Kline",
            "Jacobson",
            "Woodard",
            "Huang",
            "Kemp",
            "Mosley",
            "Prince",
            "Merritt",
            "Hurst",
            "Villanueva",
            "Roach",
            "Nolan",
            "Lam",
            "Yoder",
            "Mccullough",
            "Lester",
            "Santana",
            "Valenzuela",
            "Winters",
            "Barrera",
            "Leach",
            "Orr",
            "Berger",
            "Mckee",
            "Strong",
            "Conway",
            "Stein",
            "Whitehead",
            "Bullock",
            "Escobar",
            "Knox",
            "Meadows",
            "Solomon",
            "Velez",
            "Odonnell",
            "Kerr",
            "Stout",
            "Blankenship",
            "Browning",
            "Kent",
            "Lozano",
            "Bartlett",
            "Pruitt",
            "Buck",
            "Barr",
            "Gaines",
            "Durham",
            "Gentry",
            "Mcintyre",
            "Sloan",
            "Rocha",
            "Melendez",
            "Herman",
            "Sexton",
            "Moon",
            "Hendricks",
            "Rangel",
            "Stark",
            "Lowery",
            "Hardin",
            "Hull",
            "Sellers",
            "Ellison",
            "Calhoun",
            "Gillespie",
            "Mora",
            "Knapp",
            "Mccall",
            "Morse",
            "Dorsey",
            "Weeks",
            "Nielsen",
            "Livingston",
            "Leblanc",
            "Mclean",
            "Bradshaw",
            "Glass",
            "Middleton",
            "Buckley",
            "Schaefer",
            "Frost",
            "Howe",
            "House",
            "Mcintosh",
            "Ho",
            "Pennington",
            "Reilly",
            "Hebert",
            "Mcfarland",
            "Hickman",
            "Noble",
            "Spears",
            "Conrad",
            "Arias",
            "Galvan",
            "Velazquez",
            "Huynh",
            "Frederick",
            "Randolph",
            "Cantu",
            "Fitzpatrick",
            "Mahoney",
            "Peck",
            "Villa",
            "Michael",
            "Donovan",
            "Mcconnell",
            "Walls",
            "Boyle",
            "Mayer",
            "Zuniga",
            "Giles",
            "Pineda",
            "Pace",
            "Hurley",
            "Mays",
            "Mcmillan",
            "Crosby",
            "Ayers",
            "Case",
            "Bentley",
            "Shepard",
            "Everett",
            "Pugh",
            "David",
            "Mcmahon",
            "Dunlap",
            "Bender",
            "Hahn",
            "Harding",
            "Acevedo",
            "Raymond",
            "Blackburn",
            "Duffy",
            "Landry",
            "Dougherty",
            "Bautista",
            "Shah",
            "Potts",
            "Arroyo",
            "Valentine",
            "Meza",
            "Gould",
            "Vaughan",
            "Fry",
            "Rush",
            "Avery",
            "Herring",
            "Dodson",
            "Clements",
            "Sampson",
            "Tapia",
            "Bean",
            "Lynn",
            "Crane",
            "Farley",
            "Cisneros",
            "Benton",
            "Ashley",
            "Mckay",
            "Finley",
            "Best",
            "Blevins",
            "Friedman",
            "Moses",
            "Sosa",
            "Blanchard",
            "Huber",
            "Frye",
            "Krueger",
            "Bernard",
            "Rosario",
            "Rubio",
            "Mullen",
            "Benjamin",
            "Haley",
            "Chung",
            "Moyer",
            "Choi",
            "Horne",
            "Yu",
            "Woodward",
            "Ali",
            "Nixon",
            "Hayden",
            "Rivers",
            "Estes",
            "Mccarty",
            "Richmond",
            "Stuart",
            "Maynard",
            "Brandt",
            "Oconnell",
            "Hanna",
            "Sanford",
            "Sheppard",
            "Church",
            "Burch",
            "Levy",
            "Rasmussen",
            "Coffey",
            "Ponce",
            "Faulkner",
            "Donaldson",
            "Schmitt",
            "Novak",
            "Costa",
            "Montes",
            "Booker",
            "Cordova",
            "Waller",
            "Arellano",
            "Maddox",
            "Mata",
            "Bonilla",
            "Stanton",
            "Compton",
            "Kaufman",
            "Dudley",
            "Mcpherson",
            "Beltran",
            "Dickson",
            "Mccann",
            "Villegas",
            "Proctor",
            "Hester",
            "Cantrell",
            "Daugherty",
            "Cherry",
            "Bray",
            "Davila",
            "Rowland",
            "Levine",
            "Madden",
            "Spence",
            "Good",
            "Irwin",
            "Werner",
            "Krause",
            "Petty",
            "Whitney",
            "Baird",
            "Hooper",
            "Pollard",
            "Zavala",
            "Jarvis",
            "Holden",
            "Haas",
            "Hendrix",
            "Mcgrath",
            "Bird",
            "Lucero",
            "Terrell",
            "Riggs",
            "Joyce",
            "Mercer",
            "Rollins",
            "Galloway",
            "Duke",
            "Odom",
            "Andersen",
            "Downs",
            "Hatfield",
            "Benitez",
            "Archer",
            "Huerta",
            "Travis",
            "Mcneil",
            "Hinton",
            "Zhang",
            "Hays",
            "Mayo",
            "Fritz",
            "Branch",
            "Mooney",
            "Ewing",
            "Ritter",
            "Esparza",
            "Frey",
            "Braun",
            "Gay",
            "Riddle",
            "Haney",
            "Kaiser",
            "Holder",
            "Chaney",
            "Mcknight",
            "Gamble",
            "Vang",
            "Cooley",
            "Carney",
            "Cowan",
            "Forbes",
            "Ferrell",
            "Davies",
            "Barajas",
            "Shea",
            "Osborn",
            "Bright",
            "Cuevas",
            "Bolton",
            "Murillo",
            "Lutz",
            "Duarte",
            "Kidd",
            "Key",
            "Phoang"
    };

    private static String[] locations = {
            "Prairie Ridge",
            "Edison",
            "Packwood",
            "Wautauga Beach",
            "Harper",
            "Telma",
            "Kahlotus",
            "Mondovi",
            "Washtucna",
            "Pleasant Hill",
            "Toledo",
            "Wabash",
            "Renton",
            "Chehalis",
            "Marcellus",
            "Central Valley",
            "Ralston",
            "Lake City",
            "Megler",
            "Alder",
            "Goose Prairie",
            "Belvedere",
            "Waverly",
            "Turner Corner",
            "Lofall",
            "Kennydale",
            "Easton",
            "Navy Yard City",
            "Mercer Island",
            "Lynnwood",
            "Coulee City",
            "Douglas",
            "Centralia",
            "Colbert",
            "Bryn Mawr",
            "Silverdale",
            "Lyle",
            "Malott",
            "Mountlake Terrace",
            "Ilwaco",
            "Fairwood",
            "Warm Beach",
            "Thomas",
            "Parker",
            "Steptoe",
            "Vail",
            "Magnolia Beach",
            "Lakeview",
            "Shaw Island",
            "Oakesdale",
            "Rosburg",
            "Seattle",
            "Onalaska",
            "George",
            "Index",
            "Winchester",
            "Chelatchie",
            "Allentown",
            "Novelty",
            "Rosalia",
            "Richmond Beach",
            "Lakota",
            "Liberty Lake",
            "Airway Heights",
            "Reardan",
            "Farmer",
            "Brier",
            "Robe",
            "Elk Plain",
            "Port Townsend",
            "Ocean City",
            "Boulevard Park",
            "Newhalem",
            "Ford",
            "Waterville",
            "Quinault",
            "Humptulips",
            "Hamilton",
            "Oak Harbor",
            "Naches",
            "Hooper",
            "Anacortes",
            "Kettle Falls",
            "Walnut Grove",
            "Salkum",
            "Cunningham",
            "Irby",
            "Electric City",
            "Burbank",
            "Silver Lake",
            "Dash Point",
            "Pataha",
            "Laurel",
            "Woods Creek",
            "McKenna",
            "Revere",
            "Kalama",
            "Grandview",
            "Winthrop",
            "Maltby",
            "Spangle",
            "Blanchard",
            "Artondale",
            "May Creek",
            "Home",
            "Vashon",
            "Snoqualmie Falls",
            "Laurier",
            "Quincy",
            "Lake McMurray",
            "Martha Lake",
            "Ariel",
            "Loon Lake",
            "Thornton",
            "Starbuck",
            "Ronald",
            "Kelso",
            "Meadowdale",
            "Cottage Lake",
            "Cheney",
            "Woodway",
            "Lacey",
            "Harrah",
            "Allyn",
            "South Bend",
            "Barstow",
            "Tiger",
            "Warden",
            "Junction City",
            "Blyn",
            "Lakebay",
            "Tahuya",
            "Waukon",
            "Kitsap Lake",
            "Sultan",
            "Plain",
            "Tanner",
            "Stehekin",
            "Edmonds",
            "North Hill",
            "Zillah",
            "Monse",
            "Lake Forest Park",
            "Chinook",
            "Albion",
            "Skykomish",
            "Yakima",
            "Pacific",
            "Wishram",
            "Cascade Valley",
            "Cathcart",
            "Brush Prairie",
            "Amboy",
            "Centerville",
            "Verlot",
            "Alstown",
            "Synarep",
            "Annapolis",
            "Port Gamble",
            "Eatonville",
            "Similk Beach",
            "Cougar",
            "Eglon",
            "Paterson",
            "Tenino",
            "Minnehaha",
            "Raymond",
            "Alger",
            "Roy",
            "Almira",
            "Fragaria",
            "Green Bluff",
            "Woodmont Beach",
            "Frances",
            "Lynden",
            "Clayton",
            "Everson",
            "White Swan",
            "Camano",
            "Cedar Grove",
            "Winton",
            "East Olympia",
            "Sunset Beach",
            "Belfair",
            "Oso",
            "Federal Way",
            "Scandia",
            "Quilcene",
            "Covada",
            "Keyport",
            "Juanita",
            "Molson",
            "Daisy",
            "Sumas",
            "Mill Creek",
            "Lakewood",
            "Venersborg",
            "West Lake Sammamish",
            "Port Angeles",
            "Longview",
            "Fairmont",
            "Wapato",
            "East Port Orchard",
            "North Omak",
            "East Farms",
            "Eschbach",
            "Chattaroy",
            "Inchelium",
            "Maxwelton",
            "White Center",
            "Medical Lake",
            "Lyman",
            "Arlington",
            "Ruston",
            "McCleary",
            "Sammamish",
            "Covington",
            "McMillin",
            "La Grande",
            "Cromwell",
            "Berrydale",
            "Wenatchee",
            "Urban",
            "Maplewood",
            "Marys Corner",
            "Mattawa",
            "Cove",
            "Chico",
            "Maple Falls",
            "Colvos",
            "Ames Lake",
            "Ellisforde",
            "Selah",
            "Pine Lake",
            "Tampico",
            "Colton",
            "Usk",
            "Cle Elum",
            "Omak",
            "Eureka",
            "Harrington",
            "Sedro-Woolley",
            "Cherry Grove",
            "La Push",
            "Lake Ketchum",
            "Arletta",
            "Opportunity",
            "Glenoma",
            "Curlew",
            "Hartline",
            "Midland",
            "Adna",
            "Roslyn",
            "Deer Park",
            "Tracyton",
            "Hunts Point",
            "Koontzville",
            "Fruitland",
            "Chewelah",
            "Mohler",
            "East Renton Highlands",
            "Sunnyside",
            "Long Lake",
            "Wauna",
            "Liberty",
            "Normandy Park",
            "Mirrormont",
            "Parkwood",
            "Jamestown",
            "Forks",
            "Wallula",
            "Nighthawk",
            "SeaTac",
            "Royal City",
            "Beaux Arts Village",
            "Steilacoom",
            "Northport",
            "Eldon",
            "Ridgefield",
            "Ryderwood",
            "Manchester",
            "Vashon Heights",
            "Salmon Creek",
            "Vantage",
            "Creston",
            "Soap Lake",
            "Silver Firs",
            "Plaza",
            "Machias",
            "Neah Bay",
            "Malo",
            "Clyde Hill",
            "Marlin",
            "North Yelm",
            "Grand Coulee",
            "Outlook",
            "Clinton",
            "Evans",
            "Browns Point",
            "Kennewick",
            "North Marysville",
            "Beaver Valley",
            "Ahtanum",
            "Carbonado",
            "Hyak",
            "Arlington Heights",
            "North Sultan",
            "Pullman",
            "Wymer",
            "Adelaide",
            "Peaceful Valley",
            "West Richland",
            "Fife Heights",
            "Manson",
            "Sprague",
            "Cosmopolis",
            "Redondo",
            "Waller",
            "Addy",
            "Matlock",
            "Longbranch",
            "North Bonneville",
            "Pomeroy",
            "Colville",
            "Palmer",
            "Skyway",
            "Medina",
            "Algona",
            "Nine Mile Falls",
            "Black Diamond",
            "Gold Bar",
            "Mesa",
            "Cavalero Corner",
            "Lilliwaup",
            "La Conner",
            "Sheridan Beach",
            "Emden",
            "Markham",
            "Eltopia",
            "Stevenson",
            "Greenwater",
            "Copalis Beach",
            "Roosevelt",
            "La Crosse",
            "Summit",
            "Ohop",
            "Malden",
            "Beverly",
            "Prosser",
            "Lake Roesiger",
            "Fern Prairie",
            "Maple Valley",
            "Gifford",
            "Auburn",
            "Burton",
            "Kewa",
            "Carrolls",
            "Bayne",
            "East Cathlamet",
            "Purdy",
            "Kapowsin",
            "Ketron",
            "Connell",
            "Lincoln",
            "Clear Lake",
            "Kittitas",
            "Bucoda",
            "Ardenvoir",
            "Ellisport",
            "Bainbridge Island",
            "Danville",
            "Hazelwood",
            "Holly",
            "Valley",
            "Republic",
            "Odessa",
            "Edgewood",
            "Burlington",
            "Rice",
            "Marengo",
            "Cusick",
            "Virginia",
            "Concrete",
            "Langley",
            "Othello",
            "North City",
            "Hazel Dell",
            "Colfax",
            "Metaline",
            "Randle",
            "Millwood",
            "Snoqualmie Pass",
            "Bangor",
            "Thorp",
            "Tahlequah",
            "Prescott",
            "Buckley",
            "Dalkena",
            "Leland",
            "Fruitvale",
            "Port Hadlock",
            "University Place",
            "Morton",
            "Deep River",
            "Elberton",
            "Kingston",
            "Silverton",
            "Vader",
            "Donald",
            "Miles",
            "Asotin",
            "Joyce",
            "Eagledale",
            "Port Ludlow",
            "Loomis",
            "New London",
            "Desert Aire",
            "Poulsbo",
            "Cedonia",
            "Union",
            "Suquamish",
            "Deep Creek",
            "Yoman",
            "Cordell",
            "Hoquiam",
            "Hay",
            "Nespelem",
            "Ephrata",
            "Kent",
            "Mukilteo",
            "Boise",
            "Kirkland",
            "Waitsburg",
            "Ridgecrest",
            "Freeman",
            "Dallesport",
            "Redmond",
            "Wilkeson",
            "Sisco Heights",
            "Lewisville",
            "Kennard Corner",
            "Benge",
            "Granger",
            "Yarrow Point",
            "Lost Creek",
            "Moxee City",
            "Hockinson",
            "Oakville",
            "Tukwila",
            "Mabana",
            "Kangley",
            "Clallam Bay",
            "Newport",
            "Enetai",
            "Clearview",
            "Sahalee",
            "Yelm",
            "Midway",
            "Olympia",
            "Endicott",
            "Lind",
            "Fife",
            "Newport Hills",
            "Upper Mill",
            "Upper Preston",
            "Pateros",
            "Nordland",
            "Tyler",
            "Camden",
            "Palisades",
            "Rockport",
            "Port Orchard",
            "Preston",
            "Tieton",
            "Rochester",
            "Bingen",
            "Harbour Pointe",
            "Wellpinit",
            "Glacier",
            "Farmington",
            "Eastsound",
            "Central Park",
            "Bremerton",
            "Friday Harbor",
            "Carnation",
            "Lake Shore",
            "Houghton",
            "Lester",
            "Lake Stevens",
            "Mineral",
            "Lake Stickney",
            "Acme",
            "Oyehut",
            "Mossyrock",
            "Bridgeport",
            "Fobes Hill",
            "Rosario",
            "Brewster",
            "Fox Island",
            "Canyon Park",
            "Rock Island",
            "High Rock",
            "Rockford",
            "Erlands Point",
            "Montesano",
            "Gorst",
            "Johnson",
            "Alderton",
            "Dusty",
            "Tekoa",
            "Bay Center",
            "La Center",
            "Mazama",
            "Selleck",
            "Amanda Park",
            "Doris",
            "Sunnydale",
            "Van Zandt",
            "McDonald",
            "Moclips",
            "Ocean Park",
            "West Valley",
            "Thompson Place",
            "Dungeness",
            "Birch Bay",
            "Stratford",
            "Ione",
            "Tacoma",
            "Barberton",
            "Yacolt",
            "Coulee Dam",
            "Almota",
            "Skamokawa",
            "Woodinville",
            "Swinomish Village",
            "Methow",
            "Bay View",
            "Newaukum",
            "Kalaloch",
            "Meadow Glade",
            "Disautel",
            "Copalis Crossing",
            "Burley",
            "Riverside",
            "Ocean Shores",
            "Bethel",
            "Grisdale",
            "South Hill",
            "Island View",
            "Winona",
            "Leadpoint",
            "Brooklyn",
            "Mansfield",
            "Sequim",
            "Esperance",
            "Springdale",
            "Okanogan",
            "Cedar Mountain",
            "Moses Lake",
            "Littlerock",
            "Trentwood",
            "Mabton",
            "Klickitat",
            "Puyallup",
            "Cinebar",
            "San de Fuca",
            "Cathlamet",
            "Richardson",
            "Sumner",
            "Davenport",
            "Cliffdell",
            "Fall City",
            "Dockton",
            "Conway",
            "Marshall",
            "Walla Walla",
            "Canterwood",
            "Lexington",
            "Country Homes",
            "Altoona",
            "South Cle Elum",
            "Waldron",
            "Chesaw",
            "Sunnyslope",
            "Olympic View",
            "Hood",
            "Elbe",
            "Venice",
            "Cumberland",
            "Ostrander",
            "Cohassett Beach",
            "Deming",
            "Sekiu",
            "Terrace Heights",
            "Nemah",
            "Neilton",
            "Grays River",
            "Ashford",
            "Boistfort",
            "Shore Acres",
            "Bothell",
            "South Broadway",
            "Edwall",
            "Georgetown",
            "Maryhill",
            "Huntsville",
            "Greenbank",
            "Murphys Corner",
            "Tokeland",
            "Felida",
            "Fairview",
            "Tumwater",
            "Uniontown",
            "Coupeville",
            "River Road",
            "Duvall",
            "Marcus",
            "Seattle Heights",
            "Strandell",
            "Key Center",
            "Hanford",
            "Grand Mound",
            "Taholah",
            "Port Blakely",
            "Malone",
            "Boston Harbor",
            "Rainier",
            "Menlo",
            "Azwell",
            "Glendale",
            "Monroe",
            "Sawyer",
            "Clarkston",
            "Spanaway",
            "Gig Harbor",
            "Big Lake",
            "Smyrna",
            "Carlton",
            "Monitor",
            "Des Moines",
            "Lucerne",
            "Carlisle",
            "Metaline Falls",
            "Breidablick",
            "Snohomish",
            "Richland",
            "Parkland",
            "Veradale",
            "Kummer",
            "Woodland",
            "Washougal",
            "Boyds",
            "Bonney Lake",
            "South Prairie",
            "Larimers Corner",
            "Porter",
            "Lisabeula",
            "Saint John",
            "Spokane Valley",
            "Lake Cavanaugh",
            "Bellevue",
            "Custer",
            "Orcas",
            "Diablo",
            "Christopher",
            "Midvale Corner",
            "Marysville",
            "Newcastle",
            "North Bend",
            "Snoqualmie",
            "Three Lakes",
            "Kendall",
            "Kanaskat",
            "Schrag",
            "Wilbur",
            "Enumclaw",
            "Nile",
            "Alderwood Manor",
            "Clarkston Heights",
            "Pacific Beach",
            "Napavine",
            "Hatton",
            "Shelton",
            "Chimacum",
            "Naselle",
            "Grotto",
            "Sunrise Beach",
            "Bellingham",
            "Castle Rock",
            "Pine City",
            "Nooksack",
            "Elma",
            "Kenmore",
            "Ellensburg",
            "Belmont",
            "DuPont",
            "Long Beach",
            "Seabeck",
            "Granite Falls",
            "Tonasket",
            "Otis Orchards",
            "Milton",
            "West Pasco",
            "Badger",
            "Lamont",
            "Ravensdale",
            "Rollingbay",
            "Rocky Point",
            "Garrett",
            "Palouse",
            "Grayland",
            "Gilberton",
            "Withrow",
            "Stanwood",
            "Ayer",
            "Sudden Valley",
            "Meridian",
            "Aberdeen Gardens",
            "Possession",
            "Benton City",
            "Bickleton",
            "Elmer City",
            "Doty",
            "East Wenatchee",
            "Newman Lake",
            "Freeland",
            "Indianola",
            "Cowiche",
            "Husum",
            "Alderdale",
            "Lamona",
            "Skokomish",
            "Vaughn",
            "Ruby",
            "Bryant",
            "Coalfield",
            "Swede Heaven",
            "Spokane",
            "Brady",
            "Spring Glen",
            "Hoodsport",
            "Leavenworth",
            "Tanglewilde",
            "Bow",
            "Carlsborg",
            "North Lynnwood",
            "Cedar Falls",
            "Chelan",
            "Wilson Creek",
            "Latah",
            "Brownsville",
            "Amber",
            "Zenith",
            "Goodnoe Hills",
            "Camas",
            "Olalla",
            "Basin City",
            "Blaine",
            "Oroville",
            "Orchards",
            "Union Gap",
            "Mead",
            "Manzanita",
            "Pasco",
            "Touchet",
            "Pe Ell",
            "Baring",
            "Sappho",
            "Hunters",
            "Gleed",
            "Fairfield",
            "Torboy",
            "Cashmere",
            "Willapa",
            "Issaquah",
            "Toppenish",
            "Finley",
            "Darrington",
            "Picnic Point",
            "Aeneas",
            "Cedarhurst",
            "Four Lakes",
            "Dayton",
            "Port Madison",
            "Orting",
            "Wheeler",
            "Fircrest",
            "Lebam",
            "Marrowstone",
            "North Puyallup",
            "Five Corners",
            "Graham",
            "Longview Heights",
            "Hobart",
            "Point Roberts",
            "Town and Country",
            "Lake Hills",
            "Rosedale",
            "Irondale",
            "Dishman",
            "Bayview",
            "Conconully",
            "Entiat",
            "Lochsloy",
            "Brinnon",
            "Seahurst",
            "Dixie",
            "Eastgate",
            "Blockhouse",
            "Buena",
            "Grapeview",
            "Startup",
            "Hayford",
            "Bell Hill",
            "Westport",
            "Southworth",
            "Twisp",
            "Milan",
            "Ritzville",
            "Lake Goodwin",
            "McMurray",
            "Portage",
            "Lake Bosworth",
            "Fords Prairie",
            "Longmire",
            "Carson",
            "Mount Vista",
            "Vancouver",
            "Chelan Falls",
            "Espanola",
            "Battle Ground",
            "Summitview",
            "Geneva",
            "Queets",
            "Wollochet",
            "College Place",
            "Garfield",
            "Ruff",
            "Ewan",
            "Glenwood",
            "Riverbend",
            "Trout Lake",
            "Mount Vernon",
            "Ferndale",
            "Hansville",
            "Wickersham",
            "White Salmon",
            "Oysterville",
            "Aberdeen",
            "Melbourne",
            "Plymouth",
            "Winlock",
            "Satsop",
            "Merritt",
            "Shoreline",
            "Peshastin",
            "Marble",
            "South Snohomish",
            "Richmond Highlands",
            "Goldendale",
            "Nisqually",
            "Tillicum",
            "Anatone",
            "Tulalip",
            "Orient",
            "Dieringer",
            "Frederickson",
            "Keller",
            "Marblemount",
            "Turner",
            "Silvana",
            "Everett",
            "Burien",
            "Riner",
            "Powhatan",
            "Natural Bridge",
            "Chamberlayne Heights",
            "Manassas Park",
            "McClure",
            "Brownsburg",
            "Burgess",
            "Lake Barcroft",
            "Clover",
            "Columbia",
            "Verona",
            "Fairfax",
            "Falmouth",
            "Scottsburg",
            "Ashburn",
            "Big Stone Gap",
            "Gwynn",
            "Jewell Valley",
            "Waynesboro",
            "University Heights",
            "Batesville",
            "Whitetop",
            "Nellysford",
            "Montrose",
            "Lexington",
            "Clinchco",
            "Dante",
            "Ivor",
            "Montross",
            "Wintergreen",
            "Vesta",
            "Henry",
            "Jonesville",
            "Evington",
            "Duffield",
            "McKenney",
            "Fancy Gap",
            "Goshen",
            "Onley",
            "Exmore",
            "Schuyler",
            "Kenbridge",
            "Penhook",
            "Mollusk",
            "Toga",
            "Laurel Park",
            "Bayside",
            "Lignum",
            "Winchester",
            "Lebanon",
            "Tysons",
            "Mappsburg",
            "Orange",
            "Midlothian",
            "Calverton",
            "Fulks Run",
            "Amelia Court House",
            "Boydton",
            "Konnarock",
            "Kilmarnock",
            "Crockett",
            "Buckingham",
            "Hamilton",
            "Broadlands",
            "Mineral",
            "Apple Grove",
            "Susan",
            "Free Union",
            "Keokee",
            "Cleveland",
            "Fairfax Station",
            "Bensley",
            "Lebanon Church",
            "Brumley Gap",
            "Patrick Springs",
            "Wachapreague",
            "Spencer",
            "Gressitt",
            "Commonwealth",
            "Oak Level",
            "Adwolf",
            "Cana",
            "Haynesville",
            "Jarratt",
            "Strasburg",
            "Charles City",
            "Rose Hill Farms",
            "Radford",
            "Savageville",
            "Emory",
            "Cartersville",
            "Apple Mountain Lake",
            "Richmond",
            "Barracks",
            "Alberta",
            "Luray",
            "Middleburg",
            "Centreville",
            "Sherando",
            "Kire",
            "Drakes Branch",
            "Wicomico Church",
            "Short Pump",
            "Fairview Beach",
            "Lunenburg",
            "Mustoe",
            "Chilhowie",
            "Newington",
            "Greenbush",
            "Glen Lyn",
            "Ridgeway",
            "Gargatha",
            "Massanutten",
            "Rustburg",
            "Providence Forge",
            "Boykins",
            "Lee Mont",
            "Monterey",
            "Dungannon",
            "Wilderness",
            "Allisonia",
            "Rose Hill",
            "Bowling Green",
            "Mappsville",
            "Mountain Road",
            "Virginia Beach"
    };

}
